// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJMHxvf4Rwh3brdHwdlTnRH95XssqWuBk',
    appId: '1:1036193402414:web:03daedf7525bb558ca59bf',
    messagingSenderId: '1036193402414',
    projectId: 'sportbook-7ad49',
    authDomain: 'sportbook-7ad49.firebaseapp.com',
    storageBucket: 'sportbook-7ad49.firebasestorage.app',
    measurementId: 'G-6FWLX2QRCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo8MiPJSy3nnsHEE297638d2QYKU1WbDo',
    appId: '1:1036193402414:android:81f9c282f620d79dca59bf',
    messagingSenderId: '1036193402414',
    projectId: 'sportbook-7ad49',
    storageBucket: 'sportbook-7ad49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOkSi7tVMa4TKTuxnppGdQVvCpu6MaKLY',
    appId: '1:1036193402414:ios:23f9218cd0033e9eca59bf',
    messagingSenderId: '1036193402414',
    projectId: 'sportbook-7ad49',
    storageBucket: 'sportbook-7ad49.firebasestorage.app',
    androidClientId: '1036193402414-7efl3q68ma37mct2t8ng1hd1g1808rt6.apps.googleusercontent.com',
    iosClientId: '1036193402414-1f50mm82d6fl7c0t8d53cakoatj4i57t.apps.googleusercontent.com',
    iosBundleId: 'com.kongchansila.sportbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOkSi7tVMa4TKTuxnppGdQVvCpu6MaKLY',
    appId: '1:1036193402414:ios:23f9218cd0033e9eca59bf',
    messagingSenderId: '1036193402414',
    projectId: 'sportbook-7ad49',
    storageBucket: 'sportbook-7ad49.firebasestorage.app',
    androidClientId: '1036193402414-7efl3q68ma37mct2t8ng1hd1g1808rt6.apps.googleusercontent.com',
    iosClientId: '1036193402414-1f50mm82d6fl7c0t8d53cakoatj4i57t.apps.googleusercontent.com',
    iosBundleId: 'com.kongchansila.sportbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJMHxvf4Rwh3brdHwdlTnRH95XssqWuBk',
    appId: '1:1036193402414:web:38490d410f345463ca59bf',
    messagingSenderId: '1036193402414',
    projectId: 'sportbook-7ad49',
    authDomain: 'sportbook-7ad49.firebaseapp.com',
    storageBucket: 'sportbook-7ad49.firebasestorage.app',
    measurementId: 'G-K4X71B2FXX',
  );
}
